apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    service: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    service: {{ .Chart.Name }}
  ports:
    - name: http
      port: {{ pluck .Values.werf.env .Values.ports.http | first | default .Values.ports.http._default }}
      targetPort: {{ pluck .Values.werf.env .Values.ports.http | first | default .Values.ports.http._default }}
      protocol: TCP
